
PLATFORM_SRCS := Samples/CommonSrc/Platform/Platform.cpp Samples/CommonSrc/Platform/X11_Platform.cpp

RENDER_SRCS := Samples/CommonSrc/Render/Render_Device.cpp Samples/CommonSrc/Render/Render_Stereo.cpp \
               Samples/CommonSrc/Render/Render_GL_Device.cpp \
               Samples/CommonSrc/Render/Render_LoadTextureTGA.cpp

