package com.oculusvr.api;
import com.sun.jna.Structure;
import com.sun.jna.ptr.ShortByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : OVR_CAPI.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ovrDistortionMesh_ extends Structure {
  /** C type : ovrDistortionVertex* */
  public com.oculusvr.api.ovrDistortionVertex_.ByReference pVertexData;
  /** C type : unsigned short* */
  public ShortByReference pIndexData;
  public int VertexCount;
  public int IndexCount;
  public ovrDistortionMesh_() {
    super();
  }
  protected List<? > getFieldOrder() {
    return Arrays.asList("pVertexData", "pIndexData", "VertexCount", "IndexCount");
  }
  /**
   * @param pVertexData C type : ovrDistortionVertex*<br>
   * @param pIndexData C type : unsigned short*
   */
  public ovrDistortionMesh_(com.oculusvr.api.ovrDistortionVertex_.ByReference pVertexData, ShortByReference pIndexData, int VertexCount, int IndexCount) {
    super();
    this.pVertexData = pVertexData;
    this.pIndexData = pIndexData;
    this.VertexCount = VertexCount;
    this.IndexCount = IndexCount;
  }
  public static class ByReference extends ovrDistortionMesh_ implements Structure.ByReference {
    
  };
  public static class ByValue extends ovrDistortionMesh_ implements Structure.ByValue {
    
  };
}
