package com.oculusvr.api;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : OVR_CAPI.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ovrEyeDesc_ extends Structure {
  /**
   * @see ovrEyeType<br>
   * C type : ovrEyeType
   */
  public int Eye;
  /**
   * Absolute size of render texture.<br>
   * C type : ovrSizei
   */
  public ovrSizei_ TextureSize;
  /**
   * Viewport within texture where eye rendering takes place.<br>
   * C type : ovrRecti
   */
  public ovrRecti_ RenderViewport;
  /**
   * If specified as (0,0,0,0), it will be initialized to TextureSize.<br>
   * C type : ovrFovPort
   */
  public ovrFovPort_ Fov;
  public ovrEyeDesc_() {
    super();
  }
  protected List<? > getFieldOrder() {
    return Arrays.asList("Eye", "TextureSize", "RenderViewport", "Fov");
  }
  /**
   * @param Eye @see ovrEyeType<br>
   * C type : ovrEyeType<br>
   * @param TextureSize Absolute size of render texture.<br>
   * C type : ovrSizei<br>
   * @param RenderViewport Viewport within texture where eye rendering takes place.<br>
   * C type : ovrRecti<br>
   * @param Fov If specified as (0,0,0,0), it will be initialized to TextureSize.<br>
   * C type : ovrFovPort
   */
  public ovrEyeDesc_(int Eye, ovrSizei_ TextureSize, ovrRecti_ RenderViewport, ovrFovPort_ Fov) {
    super();
    this.Eye = Eye;
    this.TextureSize = TextureSize;
    this.RenderViewport = RenderViewport;
    this.Fov = Fov;
  }
  public static class ByReference extends ovrEyeDesc_ implements Structure.ByReference {
    
  };
  public static class ByValue extends ovrEyeDesc_ implements Structure.ByValue {
    
  };
}
