package com.oculusvr.api;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : OVR_CAPI.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ovrEyeRenderDesc_ extends Structure {
  /** C type : ovrEyeDesc */
  public ovrEyeDesc_ Desc;
  /**
   * Distortion viewport<br>
   * C type : ovrRecti
   */
  public ovrRecti_ DistortedViewport;
  /**
   * How many display pixels will fit in tan(angle) = 1.<br>
   * C type : ovrVector2f
   */
  public ovrVector2f_ PixelsPerTanAngleAtCenter;
  /**
   * Translation to be applied to view matrix.<br>
   * C type : ovrVector3f
   */
  public ovrVector3f_ ViewAdjust;
  public ovrEyeRenderDesc_() {
    super();
  }
  protected List<? > getFieldOrder() {
    return Arrays.asList("Desc", "DistortedViewport", "PixelsPerTanAngleAtCenter", "ViewAdjust");
  }
  /**
   * @param Desc C type : ovrEyeDesc<br>
   * @param DistortedViewport Distortion viewport<br>
   * C type : ovrRecti<br>
   * @param PixelsPerTanAngleAtCenter How many display pixels will fit in tan(angle) = 1.<br>
   * C type : ovrVector2f<br>
   * @param ViewAdjust Translation to be applied to view matrix.<br>
   * C type : ovrVector3f
   */
  public ovrEyeRenderDesc_(ovrEyeDesc_ Desc, ovrRecti_ DistortedViewport, ovrVector2f_ PixelsPerTanAngleAtCenter, ovrVector3f_ ViewAdjust) {
    super();
    this.Desc = Desc;
    this.DistortedViewport = DistortedViewport;
    this.PixelsPerTanAngleAtCenter = PixelsPerTanAngleAtCenter;
    this.ViewAdjust = ViewAdjust;
  }
  public static class ByReference extends ovrEyeRenderDesc_ implements Structure.ByReference {
    
  };
  public static class ByValue extends ovrEyeRenderDesc_ implements Structure.ByValue {
    
  };
}
