package com.oculusvr.api;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : OVR_CAPI.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ovrFrameTiming_ extends Structure {
  /** excessive movement after pauses for loading or initialization. */
  public float DeltaSeconds;
  /** for animation timing. */
  public double ThisFrameSeconds;
  /** Absolute point when IMU expects to be sampled for this frame. */
  public double TimewarpPointSeconds;
  /** Absolute time when frame Present + GPU Flush will finish, and the next frame starts. */
  public double NextFrameSeconds;
  /** value to ovrHmd_GetSensorState() go get general orientation. */
  public double ScanoutMidpointSeconds;
  /**
   * Timing points when each eye will be scanned out to display. Used for rendering each eye.<br>
   * C type : double[2]
   */
  public double[] EyeScanoutSeconds = new double[2];
  public ovrFrameTiming_() {
    super();
  }
  protected List<? > getFieldOrder() {
    return Arrays.asList("DeltaSeconds", "ThisFrameSeconds", "TimewarpPointSeconds", "NextFrameSeconds", "ScanoutMidpointSeconds", "EyeScanoutSeconds");
  }
  /**
   * @param DeltaSeconds excessive movement after pauses for loading or initialization.<br>
   * @param ThisFrameSeconds for animation timing.<br>
   * @param TimewarpPointSeconds Absolute point when IMU expects to be sampled for this frame.<br>
   * @param NextFrameSeconds Absolute time when frame Present + GPU Flush will finish, and the next frame starts.<br>
   * @param ScanoutMidpointSeconds value to ovrHmd_GetSensorState() go get general orientation.<br>
   * @param EyeScanoutSeconds Timing points when each eye will be scanned out to display. Used for rendering each eye.<br>
   * C type : double[2]
   */
  public ovrFrameTiming_(float DeltaSeconds, double ThisFrameSeconds, double TimewarpPointSeconds, double NextFrameSeconds, double ScanoutMidpointSeconds, double EyeScanoutSeconds[]) {
    super();
    this.DeltaSeconds = DeltaSeconds;
    this.ThisFrameSeconds = ThisFrameSeconds;
    this.TimewarpPointSeconds = TimewarpPointSeconds;
    this.NextFrameSeconds = NextFrameSeconds;
    this.ScanoutMidpointSeconds = ScanoutMidpointSeconds;
    if ((EyeScanoutSeconds.length != this.EyeScanoutSeconds.length)) 
      throw new IllegalArgumentException("Wrong array size !");
    this.EyeScanoutSeconds = EyeScanoutSeconds;
  }
  public static class ByReference extends ovrFrameTiming_ implements Structure.ByReference {
    
  };
  public static class ByValue extends ovrFrameTiming_ implements Structure.ByValue {
    
  };
}
