package com.oculusvr.api;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : OVR_CAPI.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ovrSensorDesc_ extends Structure {
  /** HID Vendor and ProductId of the device. */
  public short VendorId;
  public short ProductId;
  /**
   * Sensor (and display) serial number.<br>
   * C type : char[24]
   */
  public byte[] SerialNumber = new byte[24];
  public ovrSensorDesc_() {
    super();
  }
  protected List<? > getFieldOrder() {
    return Arrays.asList("VendorId", "ProductId", "SerialNumber");
  }
  /**
   * @param VendorId HID Vendor and ProductId of the device.<br>
   * @param SerialNumber Sensor (and display) serial number.<br>
   * C type : char[24]
   */
  public ovrSensorDesc_(short VendorId, short ProductId, byte SerialNumber[]) {
    super();
    this.VendorId = VendorId;
    this.ProductId = ProductId;
    if ((SerialNumber.length != this.SerialNumber.length)) 
      throw new IllegalArgumentException("Wrong array size !");
    this.SerialNumber = SerialNumber;
  }
  public static class ByReference extends ovrSensorDesc_ implements Structure.ByReference {
    
  };
  public static class ByValue extends ovrSensorDesc_ implements Structure.ByValue {
    
  };
}
