package com.oculusvr.api;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : OVR_CAPI.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ovrVector2i_ extends Structure {
  public int x;
  public int y;
  public ovrVector2i_() {
    super();
  }
  protected List<? > getFieldOrder() {
    return Arrays.asList("x", "y");
  }
  public ovrVector2i_(int x, int y) {
    super();
    this.x = x;
    this.y = y;
  }
  public static class ByReference extends ovrVector2i_ implements Structure.ByReference {
    
  };
  public static class ByValue extends ovrVector2i_ implements Structure.ByValue {
    
  };
}
