package com.oculusvr.capi;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class DistortionVertex extends Structure {
  public Vector2f Pos;
  /** Lerp factor between time-warp matrices. Can be encoded in Pos.z. */
  public float TimeWarpFactor;
  /** Vignette fade factor. Can be encoded in Pos.w. */
  public float VignetteFactor;
  public Vector2f TexR;
  public Vector2f TexG;
  public Vector2f TexB;

  public DistortionVertex() {
    super();
  }

  @Override
  protected List<?> getFieldOrder() {
    return Arrays.asList("Pos", "TimeWarpFactor", "VignetteFactor", "TexR", "TexG", "TexB");
  }

  public DistortionVertex(Vector2f Pos, float TimeWarpFactor, float VignetteFactor, Vector2f TexR, Vector2f TexG,
      Vector2f TexB) {
    super();
    this.Pos = Pos;
    this.TimeWarpFactor = TimeWarpFactor;
    this.VignetteFactor = VignetteFactor;
    this.TexR = TexR;
    this.TexG = TexG;
    this.TexB = TexB;
  }

  public DistortionVertex(Pointer peer) {
    super(peer);
  }

  public static class ByReference extends DistortionVertex implements Structure.ByReference {

  };

  public static class ByValue extends DistortionVertex implements Structure.ByValue {

  };
}
