package com.oculusvr.capi;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class EyeRenderDesc extends Structure {
  public EyeDesc Desc;
  /** Distortion viewport */
  public Recti DistortedViewport;
  /** How many display pixels will fit in tan(angle) = 1. */
  public Vector2f PixelsPerTanAngleAtCenter;
  /** Translation to be applied to view matrix. */
  public Vector3f ViewAdjust;

  public EyeRenderDesc() {
    super();
  }

  @Override
  protected List<?> getFieldOrder() {
    return Arrays.asList("Desc", "DistortedViewport", "PixelsPerTanAngleAtCenter", "ViewAdjust");
  }

  public EyeRenderDesc(EyeDesc Desc, Recti DistortedViewport, Vector2f PixelsPerTanAngleAtCenter, Vector3f ViewAdjust) {
    super();
    this.Desc = Desc;
    this.DistortedViewport = DistortedViewport;
    this.PixelsPerTanAngleAtCenter = PixelsPerTanAngleAtCenter;
    this.ViewAdjust = ViewAdjust;
  }

  public EyeRenderDesc(Pointer peer) {
    super(peer);
  }

  public static class ByReference extends EyeRenderDesc implements Structure.ByReference {

  };

  public static class ByValue extends EyeRenderDesc implements Structure.ByValue {

  };
}
