package com.oculusvr.capi;

import com.sun.jna.Pointer;
import com.sun.jna.Union;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class GLTexture extends Union {
  public Texture Texture;
  public GLTextureData OGL;

  public GLTexture() {
    super();
  }

  public GLTexture(Texture Texture) {
    super();
    this.Texture = Texture;
    setType(Texture.class);
  }

  public GLTexture(GLTextureData OGL) {
    super();
    this.OGL = OGL;
    setType(GLTextureData.class);
  }

  public GLTexture(Pointer peer) {
    super(peer);
  }

  public static class ByReference extends GLTexture implements com.sun.jna.Structure.ByReference {

  };

  public static class ByValue extends GLTexture implements com.sun.jna.Structure.ByValue {

  };
}
