package com.oculusvr.capi;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class GLTextureData extends Structure {
  /** General device settings. */
  public TextureHeader Header;
  public int TexId;

  public GLTextureData() {
    super();
  }

  @Override
  protected List<?> getFieldOrder() {
    return Arrays.asList("Header", "TexId");
  }

  public GLTextureData(TextureHeader Header, int TexId) {
    super();
    this.Header = Header;
    this.TexId = TexId;
  }

  public GLTextureData(Pointer peer) {
    super(peer);
  }

  public static class ByReference extends GLTextureData implements Structure.ByReference {

  };

  public static class ByValue extends GLTextureData implements Structure.ByValue {

  };
}
