package com.oculusvr.capi;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class PoseStatef extends Structure {
  public Posef Pose;
  public Vector3f AngularVelocity;
  public Vector3f LinearVelocity;
  public Vector3f AngularAcceleration;
  public Vector3f LinearAcceleration;
  /** Absolute time of this state sample. */
  public double TimeInSeconds;

  public PoseStatef() {
    super();
  }

  @Override
  protected List<?> getFieldOrder() {
    return Arrays.asList("Pose", "AngularVelocity", "LinearVelocity", "AngularAcceleration", "LinearAcceleration",
        "TimeInSeconds");
  }

  public PoseStatef(Posef Pose, Vector3f AngularVelocity, Vector3f LinearVelocity, Vector3f AngularAcceleration,
      Vector3f LinearAcceleration, double TimeInSeconds) {
    super();
    this.Pose = Pose;
    this.AngularVelocity = AngularVelocity;
    this.LinearVelocity = LinearVelocity;
    this.AngularAcceleration = AngularAcceleration;
    this.LinearAcceleration = LinearAcceleration;
    this.TimeInSeconds = TimeInSeconds;
  }

  public PoseStatef(Pointer peer) {
    super(peer);
  }

  public static class ByReference extends PoseStatef implements Structure.ByReference {

  };

  public static class ByValue extends PoseStatef implements Structure.ByValue {

  };
}
