package com.oculusvr.capi;

import java.util.Arrays;
import java.util.List;

import com.oculusvr.capi.OvrLibrary.ovrRenderAPIType;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class RenderAPIConfigHeader extends Structure {
  /** @see ovrRenderAPIType */
  public int API;
  public Sizei RTSize;
  public int Multisample;

  public RenderAPIConfigHeader() {
    super();
  }

  @Override
  protected List<?> getFieldOrder() {
    return Arrays.asList("API", "RTSize", "Multisample");
  }

  public RenderAPIConfigHeader(int API, Sizei RTSize, int Multisample) {
    super();
    this.API = API;
    this.RTSize = RTSize;
    this.Multisample = Multisample;
  }

  public RenderAPIConfigHeader(Pointer peer) {
    super(peer);
  }

  public static class ByReference extends RenderAPIConfigHeader implements Structure.ByReference {

  };

  public static class ByValue extends RenderAPIConfigHeader implements Structure.ByValue {

  };
}
