package com.oculusvr.capi;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class RenderAPIConfig extends Structure {
  public RenderAPIConfigHeader Header;
  public IntByReference[] PlatformData = new IntByReference[8];

  public RenderAPIConfig() {
    super();
  }

  @Override
  protected List<?> getFieldOrder() {
    return Arrays.asList("Header", "PlatformData");
  }

  public RenderAPIConfig(RenderAPIConfigHeader Header, IntByReference PlatformData[]) {
    super();
    this.Header = Header;
    if ((PlatformData.length != this.PlatformData.length))
      throw new IllegalArgumentException("Wrong array size !");
    this.PlatformData = PlatformData;
  }

  public RenderAPIConfig(Pointer peer) {
    super(peer);
  }

  public static class ByReference extends RenderAPIConfig implements Structure.ByReference {

  };

  public static class ByValue extends RenderAPIConfig implements Structure.ByValue {

  };
}
